#!/bin/sh

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ "$(uname -m)" = "arm64" ]; then
  HOMEBREW_PREFIX="/opt/homebrew"
else
  HOMEBREW_PREFIX="/usr/local"
fi

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
    /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    export PATH="$HOMEBREW_PREFIX/bin:$PATH"
fi


# fix conflicts: only uninstall if currently installed
for remove in azure-cli aws-sam-cli; do
  if brew list --formula "$remove" >/dev/null 2>&1; then
    brew uninstall "$remove"
  fi
done

for overwrite in python@3.13 awscli bash-completion git go; do
  brew install --overwrite "$overwrite"
done

echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle -f --file=- <<EOF

tap "dteoh/sqa"
tap "hashicorp/homebrew-tap"
tap "jackielii/tap"
tap "koekeishiya/formulae"
tap "romkatv/powerlevel10k"
tap "warrensbox/homebrew-tap"

brew "ansiweather"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "bitwarden-cli"
brew "claude-code-router"
brew "colordiff"
brew "container"
brew "coreutils"
brew "docker-compose"
brew "fzf"
brew "gh"
brew "git"
brew "git-remote-codecommit"
brew "go"
brew "helm"
brew "htop"
brew "infracost"
brew "jq"
brew "kind"
brew "kubectl"
brew "k9s"
brew "kubie"
brew "lynx"
brew "mas"
brew "midnight-commander"
brew "neovim"
brew "nmap"
brew "node@22"
brew "ollama"
brew "packer"
brew "pgcli"
brew "pipenv"
brew "python@3.13"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "pstree"
brew "pyenv"
brew "qt"
brew "rclone"
brew "ripgrep"
brew "shellcheck"
brew "jackielii/tap/skhd-zig"
brew "telnet"
brew "terraform-ls"
brew "tflint"
brew "warrensbox/tap/tfswitch"
brew "thefuck"
brew "tldr"
brew "tmate"
brew "tmux"
brew "unison"
brew "watch"
brew "wget"
brew "koekeishiya/formulae/yabai"
brew "yq"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

# casks
cask "1password"
cask "antigravity"
cask "arc"
cask "audio-hijack"
cask "aws-vpn-client"
cask "github-copilot-for-xcode"
cask "claude"
cask "claude-code"
cask "cyberghost-vpn"
cask "daisydisk"
cask "discord"
cask "duckduckgo"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "grammarly-desktop"
cask "granola"
cask "hiddenbar"
cask "iterm2"
cask "keyboard-maestro"
cask "lark"
cask "lm-studio"
cask "macwhisper"
cask "nordvpn"
cask "notion"
cask "notion-calendar"
cask "obs"
cask "obsidian"
cask "opal"
cask "opencore-patcher"
cask "opera-gx"
cask "pocket-casts"
cask "raycast"
cask "session-manager-plugin"
cask "slack"
cask "spotify"
cask "superhuman"
cask "tailscale"
cask "telegram"
cask "zoom"
cask "vlc"
cask "warp"
cask "whatsapp"
EOF

if mas account >/dev/null 2>&1; then
    echo "Signed in to App Store"
    # Amphetamine
    mas install 937984704
else
    echo "Not signed in to App Store"
fi

echo "Cleaning up old Homebrew versions ..."
brew cleanup

if [ -f "$HOME/.laptop.local" ]; then
  echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090 disable=SC1091
  . "$HOME/.laptop.local"
fi

# if powerlevel10k.zsh-theme don't exist in .zshrc then add it
if ! grep -q "powerlevel10k.zsh-theme" "$HOME/.zshrc"; then
  echo "source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc
fi
