#!/bin/sh

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
    /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi


# fix conflicts
removes="
azure-cli
aws-sam-cli
"

# shellcheck disable=SC2116
for remove in $(echo "$removes"); do
  brew uninstall "$remove"
done

overwrites="
python@3.11
awscli
bash-completion
git
go
"

# shellcheck disable=SC2116
for overwrite in $(echo "$overwrites"); do
  brew install --overwrite "$overwrite"
done

echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle -f --file=- <<EOF

tap "dteoh/sqa"
tap "hashicorp/homebrew-tap"
tap "koekeishiya/formulae"
tap "romkatv/powerlevel10k"
tap "warrensbox/homebrew-tap"

brew "ansiweather"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "bitwarden-cli"
brew "colordiff"
brew "coreutils"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "helm"
brew "htop"
brew "jq"
brew "kind"
brew "k9s"
brew "kubie"
brew "lynx"
brew "midnight-commander"
brew "neovim"
brew "nmap"
brew "node@18"
brew "packer"
brew "pgcli"
brew "pipenv"
brew "powerlevel10k"
brew "pstree"
brew "pyenv"
brew "qt@5"
brew "rclone"
brew "ripgrep"
brew "shellcheck"
brew "skhd"
brew "telnet"
brew "terraform-ls"
brew "tflint"
brew "tfswitch"
brew "thefuck"
brew "tldr"
brew "tmate"
brew "tmux"
brew "unison"
brew "watch"
brew "wget"
brew "yabai"
brew "yq"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

# casks
cask "1password"
cask "android-platform-tools"
cask "audio-hijack"
cask "aws-vpn-client"
cask "barrier"
cask "brave-browser"
cask "cool-retro-term"
cask "cyberghost-vpn"
cask "daisydisk"
cask "discord"
cask "docker"
cask "duckduckgo"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "grammarly-desktop"
cask "iterm2"
cask "keepassxc"
cask "logitech-options"
cask "nordvpn"
cask "notion"
cask "notion-calendar"
cask "obs"
cask "obs-virtualcam"
cask "obsidian"
cask "opal"
cask "opencore-patcher"
cask "pgadmin4"
cask "pocket-casts"
cask "raycast"
cask "session-manager-plugin"
cask "slack"
cask "spotify"
cask "tailscale"
cask "telegram"
cask "zoom"
cask "via"
cask "vlc"
cask "whatsapp"
EOF

if [ -f "$HOME/.laptop.local" ]; then
  echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090 disable=SC1091
  . "$HOME/.laptop.local"
fi

# if powerlevel10k.zsh-theme don't exist in .zshrc then add it
if ! grep -q "powerlevel10k.zsh-theme" "$HOME/.zshrc"; then
  echo "source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc
fi
