---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update brew
        run: brew update

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Run shellcheck
        run: shellcheck mac -e SC1091

      - name: Install shfmt
        run: brew install shfmt

      - name: Check shell formatting
        run: shfmt -d -i 2 -ci mac

  install:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Run setup script (first run)
        run: sh mac

      - name: Run setup script (idempotency check)
        run: sh mac
